/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01.gradle;

import com.google.common.collect.Lists;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        Main main = new Main();
        ArrayList<String> strings = Lists.newArrayList("one", "two", "three");
        System.out.println(main.reverse(strings));
    }
}
