alphavantage:
  url: https://www.alphavantage.co/query
  apiKey: yourKey

jwt:
  secret: everythingYouWant

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false