version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend-dfile
    privileged: true
    ports:
      - "80:80"
    depends_on:
#      - backend
      - postgres
    networks:
      - nw
#  backend:
#    build:
#      context: .
#      dockerfile: backend-dfile
#    image: "backend"
#    privileged: true
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      - DB_DRIVER=org.postgresql.Driver
#      - DB_URL=jdbc:postgresql://postgres:5432/db
#      - DB_USERNAME=postgres
#      - DB_PASSWORD=postgres
#    networks:
#      - nw
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - nw
networks:
  nw: